// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.x
// LVGL version: 9.3.0
// Project name: cyd320240

#include "ui.h"

///////////////////// VARIABLES ////////////////////
lv_obj_t *ui____initial_actions0;

void ui_init(void)
{
    // Apply the default theme to the active display.
    lv_disp_t *dispp = lv_disp_get_default();
    lv_theme_t *theme = lv_theme_default_init(dispp,
                            lv_palette_main(LV_PALETTE_BLUE),
                            lv_palette_main(LV_PALETTE_RED),
                            true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);

    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
