// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.x
// LVGL version: 9.3.0
// Project name: cyd320240
//
// Event handlers.  SquareLine generates the prototypes here and you fill in
// the bodies in ui_events.c (this is the one file SquareLine never overwrites).

#ifndef _CYD320240_UI_EVENTS_H
#define _CYD320240_UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

#include "ui.h"

void ui_event_Button1(lv_event_t *e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
