// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.x
// LVGL version: 9.3.0
// Project name: cyd320240
//
// Hand-written event handler bodies.  Edit freely — SquareLine preserves this
// file across re-exports.

#include "ui.h"

void ui_event_Button1(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        static int count = 0;
        count++;
        lv_label_set_text_fmt(ui_StatusLabel, "Touched: %d", count);
    }
}
