// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.x
// LVGL version: 9.3.0
// Project name: cyd320240
//
// A trimmed subset of SquareLine's standard ui_helpers.  A fresh SquareLine
// export will replace this with the full set.

#ifndef _CYD320240_UI_HELPERS_H
#define _CYD320240_UI_HELPERS_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#define _UI_LABEL_PROPERTY_TEXT 0

#define _UI_MODIFY_FLAG_ADD     0
#define _UI_MODIFY_FLAG_REMOVE  1
#define _UI_MODIFY_FLAG_TOGGLE  2

#define _UI_MODIFY_STATE_ADD    0
#define _UI_MODIFY_STATE_REMOVE 1
#define _UI_MODIFY_STATE_TOGGLE 2

void _ui_label_set_property(lv_obj_t *target, int id, const char *val);
void _ui_flag_modify(lv_obj_t *target, int32_t flag, int value);
void _ui_state_modify(lv_obj_t *target, int32_t state, int value);
void _ui_screen_change(lv_obj_t **target, lv_screen_load_anim_t fademode,
                       int spd, int delay, void (*target_init)(void));
void _ui_screen_delete(lv_obj_t **target);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
