// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.x
// LVGL version: 9.3.0
// Project name: cyd320240

#include "ui_helpers.h"

void _ui_label_set_property(lv_obj_t *target, int id, const char *val)
{
    if (id == _UI_LABEL_PROPERTY_TEXT)
        lv_label_set_text(target, val);
}

void _ui_flag_modify(lv_obj_t *target, int32_t flag, int value)
{
    if (value == _UI_MODIFY_FLAG_TOGGLE) {
        if (lv_obj_has_flag(target, flag)) lv_obj_remove_flag(target, flag);
        else lv_obj_add_flag(target, flag);
    } else if (value == _UI_MODIFY_FLAG_ADD) {
        lv_obj_add_flag(target, flag);
    } else {
        lv_obj_remove_flag(target, flag);
    }
}

void _ui_state_modify(lv_obj_t *target, int32_t state, int value)
{
    if (value == _UI_MODIFY_STATE_TOGGLE) {
        if (lv_obj_has_state(target, state)) lv_obj_remove_state(target, state);
        else lv_obj_add_state(target, state);
    } else if (value == _UI_MODIFY_STATE_ADD) {
        lv_obj_add_state(target, state);
    } else {
        lv_obj_remove_state(target, state);
    }
}

void _ui_screen_change(lv_obj_t **target, lv_screen_load_anim_t fademode,
                       int spd, int delay, void (*target_init)(void))
{
    if (*target == NULL)
        target_init();
    lv_screen_load_anim(*target, fademode, spd, delay, false);
}

void _ui_screen_delete(lv_obj_t **target)
{
    if (*target == NULL)
        return;
    lv_obj_delete(*target);
    *target = NULL;
}
