// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.x
// LVGL version: 9.3.0
// Project name: cyd320240

#include "ui.h"

lv_obj_t *ui_Screen1 = NULL;
lv_obj_t *ui_Title = NULL;
lv_obj_t *ui_Button1 = NULL;
lv_obj_t *ui_ButtonLabel = NULL;
lv_obj_t *ui_StatusLabel = NULL;

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);

    // Title label across the top.
    ui_Title = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Title, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_Title, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_Title, LV_ALIGN_TOP_MID);
    lv_obj_set_y(ui_Title, 16);
    lv_label_set_text(ui_Title, "CYD Squareline Launcher");

    // A button that reports touches into the status label.
    ui_Button1 = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_Button1, 180);
    lv_obj_set_height(ui_Button1, 64);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_set_y(ui_Button1, -8);
    lv_obj_remove_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);

    ui_ButtonLabel = lv_label_create(ui_Button1);
    lv_obj_set_align(ui_ButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ButtonLabel, "Press me");

    // Status label near the bottom.
    ui_StatusLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_StatusLabel, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_StatusLabel, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_StatusLabel, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_y(ui_StatusLabel, -20);
    lv_label_set_text(ui_StatusLabel, "Touched: 0");

    // Wire the button up to its event handler (defined in ui_events.c).
    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
}

void ui_Screen1_screen_destroy(void)
{
    if (ui_Screen1) lv_obj_delete(ui_Screen1);

    ui_Screen1 = NULL;
    ui_Title = NULL;
    ui_Button1 = NULL;
    ui_ButtonLabel = NULL;
    ui_StatusLabel = NULL;
}
