// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.x
// LVGL version: 9.3.0
// Project name: cyd320240

#ifndef _CYD320240_UI_SCREEN1_H
#define _CYD320240_UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Title;
extern lv_obj_t *ui_Button1;
extern lv_obj_t *ui_ButtonLabel;
extern lv_obj_t *ui_StatusLabel;

void ui_Screen1_screen_init(void);
void ui_Screen1_screen_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
