/*******************************************************************************
 * CYD ESP32-2432S028 LVGL 9.3 Squareline Launcher
 *
 * For the "Cheap Yellow Display" ESP32-2432S028 (ILI9341 + XPT2046 touch).
 *
 * Demonstrates touchscreen, LVGL 9.3 and a Squareline Studio UI.
 *
 * Orientation: lv_setup.begin(rotation) accepts 0 = portrait (240x320, the
 * ILI9341's native orientation), 1 = landscape (320x240), 2 = portrait
 * flipped, 3 = landscape flipped (degrees 90/180/270 work as aliases for
 * 1/2/3).  This sketch defaults to portrait; change the argument below to
 * rotate.  Display and touch rotate together.  (If you design your Squareline
 * UI for landscape, set rotation to 1 here and size the Squareline project
 * 320x240 to match.)
 *
 * Requires the following libraries:
 *   - chipguy_cyd2432S028_display  (display + touch driver, this library)
 *   - lvgl 9.3
 *
 * Arduino IDE Board Settings:
 *   - Board: "ESP32-2432S028R CYD" (in Tools > Board > esp32) — configures the
 *     board specifics for you; no other settings needed.
 *
 ******************************************************************************/

// This is built for LVGL 9.3, which Squareline can generate UI's for.
// It's important for the version numbers to match, even if it's not newest.
#include "lv_conf.h"
#include "lvgl.h"
#include "lv_setup.hpp"

// Fonts
// The Montserrat font is built into LVGL in multiple sizes, each size takes up memory.
// We enable the 14 point font as a default font.
#define LV_FONT_MONTSERRAT_14 1
// need other sizes?  You'll know if you see compiler errors after trying to
// use them.  Just edit lv_conf.h where FONTs are turned off (0) and turn them on (1)

// The folder of UI files generated by Squareline should be in a subdirectory
// named src in the sketch folder.  The existing files are a small example.
// Simply DELETE all of the example files, and "Export" new "UI files", from Squareline.
// Using the "Arduino TFT_eSPI profile" from Squareline works (among others).
// Required Squareline project settings: 16-bit color depth, no rotation or
// offset (this library handles rotation, so keep the Squareline project
// unrotated).  Size the project to match the rotation chosen in setup() below:
//   portrait  rotation 0 or 2  ->  240x320
//   landscape rotation 1 or 3  ->  320x240
#include "src/ui.h"

void setup() {
    Serial.begin(115200);

    // Initialize display, touch, and LVGL.  Defaults to portrait; pass a
    // rotation to change it (0/2 = portrait, 1/3 = landscape; see header).
    // Match the Squareline project size to this choice (see the note above).
    lv_setup.begin();
    Serial.printf("LVGL initialized with %dx%d touchscreen\n",
                  display.width(), display.height());

    // Resistive touch varies between panels.  If touch lands in the wrong
    // place, gather raw values with lv_setup.touch().readRaw() and feed the
    // corners into lv_setup.touch().setCalibration(xMin, xMax, yMin, yMax).

    // Start the Squareline application's own setup
    ui_init();
}


void loop() {
    // Give loop control to LVGL objects created by Squareline application
    lv_timer_handler();
    delay(5);
}
